import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} `}>
      <body className="min-h-full flex flex-col">
        <div className="flex">
          <Sidebar userImg="/assets/images/user.png" />
          <div className="w-full pt-16">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
